project:
  type: website
  output-dir: docs
  resources: 
    - media/

website:
  title: "Flippers and Nucleotides"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: art.qmd
        text: Scientific Illustration

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full 

editor: visual

