project:
  type: website
  output-dir: docs
  resources: 
    - media/

website:
  title: "Mrivera104.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

